;  See https://tox.wiki/en
[tox]
requires =
    tox>=4
; run lint by default when just calling "tox"
env_list = lint

[testenv:test_data]
description = install test data
skip_install = true
allowlist_externals =
    mkdir
    wget
    unzip
    rm
commands =
    mkdir -p cwas4fmri/data/test_data
    wget --retry-connrefused \
        --waitretry=5 \
        --read-timeout=20 \
        --timeout=15 \
        -t 0 \
        -q \
        -O cwas4fmri/data/test_data/smoke_test_halfpipe_ds30.zip \
        "https://zenodo.org/records/16368481/files/smoke_test_halfpipe_ds30.zip?download=1"
    unzip cwas4fmri/data/test_data/smoke_test_halfpipe_ds30.zip -d cwas4fmri/data/test_data/
    rm cwas4fmri/data/test_data/smoke_test_halfpipe_ds30.zip
